server:
  port: 8081
  servlet:
    context-path: /api/
  
spring:
  datasource:
    url: jdbc:h2:mem:springapi?useSSL=false&serverTimezone=UTC
    driver-class-name: org.h2.Driver
    username: sa
    password: 
    
  jackson:
    time-zone: America/Sao_Paulo
      
      
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: /h2